services:
  # Apache and PHP service
  httpd:
    image: httpd:latest
    container_name: phyreamp-httpd
    networks:
      - phyreamp-network
    ports:
      - "80:80"
    volumes:
      - ./docker/html:/var/www/html
      - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - /Users/bobi/PhpstormProjects/microweber/:/var/www/html/bgmanager-dev/

  php83-fpm:
    container_name: phyreamp-php83-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      -  "9000"
    volumes:
      -   ./docker/html:/var/www/html
      - /Users/bobi/PhpstormProjects/microweber/:/var/www/html/bgmanager-dev/

    networks:
      - phyreamp-network

  # MySQL service
  mysql:
    image: mysql:8.0
    networks:
      - phyreamp-network
    container_name: phyreamp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phyreamp
      MYSQL_USER: phyreamp
      MYSQL_PASSWORD: phyreamp
    volumes:
      - ./docker/mysql-data:/var/lib/mysql

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - phyreamp-network
    container_name: phyreamp-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: phyreamp-mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

# Define networks
networks:
  phyreamp-network:
